name: Deploy to FTP

on:
  push:
    branches:
      - main  # Ujisti se, že tvá hlavní větev se jmenuje master

jobs:
  web-deploy:
    name: 🚚 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Stáhnout kód z repozitáře
        uses: actions/checkout@v4

      - name: 📂 Nahrát soubory na FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp       # Přepnuto na bezpečnější SFTP
          port: 222            # Tvůj specifický port pro SFTP
          server-dir: /www/    # Cesta na serveru
