name: Deploy to FTP

on:
  push:
    branches:
      - main  # Zde nastav větev, při které se má akce spustit

jobs:
  web-deploy:
    name: 🚚 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Stáhnout kód z repozitáře
        uses: actions/checkout@v4

      - name: 📂 Nahrát soubory na FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /www/  # Cesta na serveru, kam se má web nahrát
